obsidian_entrypoint_path_str: ./Hoisanwa/Home.md
log_output_folder_path_str: output/log
included_folders: []
exclude_glob:
  - /.obsidian
  - /.trash
  - /.DS_Store
  - /.git
max_note_depth: -1
copy_vault_to_tempdir: true
copy_vault_to_tempdir_method: default
copy_vault_to_tempdir_follow_copy: false
included_file_suffixes:
  - jpg
  - jpeg
  - gif
  - png
  - bmp
  - svg
  - mp4
  - webm
  - ogv
  - mov
  - mkv
  - mp3
  - wav
  - m4a
  - ogg
  - 3gp
  - flac
  - pdf
video_format_suffixes:
  - mp4
  - webm
  - ogv
  - mov
  - mkv
audio_format_suffixes:
  - mp3
  - webm
  - wav
  - m4a
  - ogg
  - 3gp
  - flac
embeddable_file_suffixes:
  - pdf
md_source_host_urls: []
site_name: "台山话 | Hoisanwa"
html_url_prefix: ''
html_template_path_str: ''
html_custom_inclusions: []
html_custom_footer_inclusions: []
navbar_links: []
file_exports: []
toggles:
  compile_md: true
  compile_html: true
  strict_line_breaks: false
  force_filename_to_lowercase: true
  slugify_html_links: false
  process_all: false
  verbose_printout: false
  debug_filetree_keys: false
  extended_logging: false
  allow_duplicate_filenames_in_root: true
  warn_on_skipped_image: true
  no_clean: false
  relative_path_md: true
  relative_path_html: false
  external_blank: false
  img_alt_text_use_figure: true
  preserve_inline_tags: false
  features:
    styling:
      layout: documentation
      header_template: full
      max_note_width: 88rem
      add_dir_list: true
      accent_color: 65, 76, 253
      loading_bg_color: 255, 255, 255
    theme_picker:
      enabled: true
      styling:
        show_icon: true
    code_highlight:
      enabled: true
    mermaid_diagrams:
      enabled: true
    callouts:
      enabled: true
    math_latex:
      enabled: true
    backlinks:
      enabled: false
    embedded_note_titles:
      enabled: true
      hide_on_h1: true
    search:
      enabled: true
      try_preload: false
      styling:
        show_icon: true
    embedded_search:
      enabled: false
    tags_page:
      enabled: true
      styling:
        show_icon: true
        show_in_note_footer: true
    dataview:
      enabled: false
      folder: obs.html/export
    folder_notes:
      enabled: false
      placement: outside folder
      naming: folder name
    eraser:
      enabled: true
    breadcrumbs:
      enabled: false
    graph:
      enabled: true
      templates:
        - id: 2d
          name: 2d
          path: builtin<2d>
      styling:
        show_icon: true
      coalesce_force: '-30'
      show_inclusions_in_graph: true
    rss:
      enabled: True
      host_root: 'https://hoisanwa.github.io/'
      styling: 
        show_icon: True
      channel: 
        title: '台山话 | Hoisanwa'
        website_link: 'https://hoisanwa.github.io/'
        description: 'Hoisanwa Dictionary.'
        language_code: 'zh-cn'
        managing_editor: 'hoisanwa@gmail.com'
        web_master: 'hoisanwa@gmail.com'
      items:
        selector: 
          match_keys: ['yaml','tags', ['']]
          exclude_keys: ['yaml','tags', ['type/moc']]
          include_subfolders: ['Log', 'Changelog']
          exclude_subfolders: ['.git', 'md', 'index_from_tags', 'obs.html','__src']
          exclude_files: ['not_created.html', 'index.html']
        description:
          selectors:
            - ['yaml','rss:description']
            - ['first-paragraphs', 2, '<br/><br/>']
            - ['first-header', 1]
        title: 
          selectors: 
            - ['yaml','rss:title']
            - ['first-header', 1]
            - ['path', ['parent',1], '/ ', ['stem']]
        publish_date: 
          selectors: 
            - ['yaml','rss:publish_date']
            - ['yaml_strip','tags',['date/']]
          iso_formatted: True
          format_string: '' #'%Y-%m-%d'
          default_value: '1999-12-31'
    create_index_from_dir_structure:
      enabled: true
      verbose: false
      rel_output_path: obs.html/dir_index.html
      styling:
        show_icon: true
      exclude_subfolders:
        - .git
        - __src
        - md
        - obs.html
      exclude_files:
        - .gitignore
        - favicon.ico
        - not_created.html
      homepage_label: index
    create_index_from_tags:
      enabled: true
      verbose: false
      rel_output_path: obs.html/tag_index.md
      homepage_label: index
      use_as_homepage: false
      add_links_in_graph_tree: true
      tags: ["地名", "词", "字"]
      match_on_inline_tags: false
      styling:
        include_folder_in_link: false
      sort:
        method: none
        key_path: ''
        value_prefix: ''
        reverse: false
        none_on_bottom: true
      exclude_paths:
        - .gitignore
    table_of_contents:
      add_toc_when_missing: true
    side_pane:
      right_pane:
        enabled: false
        width: 16rem
        contents: dir_tree
        content_args:
          rel_path: index.html
          div_selector: .content
          strip_sub_divs:
            - .toc
      left_pane:
        enabled: true
        width: 8rem
        contents: toc
        content_args:
          rel_path: index.html
          div_selector: .content
          strip_sub_divs:
            - .toc
    post_processing: []
md_folder_path_str: ./output/md
md_entrypoint_path_str: ./output/md/Home.md
html_output_folder_path_str: ../hoisanwa.github.io/html/
