#!/bin/sh

obsidianhtml convert -i config.yaml

REPO_DIR=../hoisanwa.github.io
cd ${REPO_DIR}
git rm -rf .
mv ./html/* .
rm -rf ./html
git -C ../hoisanwa.github.io add .
git -C ../hoisanwa.github.io commit -m "update"
git -C ../hoisanwa.github.io push origin main
# git push origin main