#!/bin/sh

GIT=`which git`
REPO_DIR=../hoisanwa.github.io
${GIT} rm -rf ../hoisanwa.github.io/*

# obsidianhtml convert -i config.yaml

# cd ${REPO_DIR}

# mv html/* ./
# rm -rf html/

# ${GIT} add .
# ${GIT} commit -m "update"
# ${GIT} push -f origin main